# Generated by Django 5.2.3 on 2025-06-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bowler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('wickets_taken', models.IntegerField()),
                ('bowling_average', models.FloatField()),
                ('bowling_strikerate', models.FloatField()),
                ('economy_rate', models.FloatField()),
            ],
        ),
    ]
